apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: ashad912/ticketing-app-auth
      context: auth
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ashad912/ticketing-app-client
      context: client
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: ashad912/ticketing-app-tickets
      context: tickets
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ashad912/ticketing-app-orders
      context: orders
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ashad912/ticketing-app-expiration
      context: expiration
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ashad912/ticketing-app-payments
      context: payments
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
