name: tests-payments

on:
  pull_request:
    paths:
      - 'ticketing-app/payments/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing-app && cd payments && npm install && npm run test:ci
      
