name: tests-auth

on:
  pull_request:
    paths:
      - 'ticketing-app/auth/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing-app && cd auth && npm install && npm run test:ci
      
