name: tests-orders

on:
  pull_request:
    paths:
      - 'ticketing-app/orders/**'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing-app && cd orders && npm install && npm run test:ci
      
